name: Automation Exercise

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main  # Explicitly checkout the main branch

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x  

    - name: Build and Run Tests
      run: |
        dotnet build "Automation Exercise.sln"  
        dotnet test "Automation Exercise.sln"
