name: Automated Tests

on:
  schedule:
    - cron: '0 0 * * *'  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0  
      - name: Install dependencies
        run: dotnet restore

      - name: Build and run tests
        run: dotnet test
